- task: GitHubComment@0
  inputs:
    gitHubConnection: 'pipeline_configration'
    repositoryName: 'https://github.com/kuk6467/GITHUB.git'
    
- trigger:
  branches:
    include:
    - main
    - releases/*
    exclude:
    - releases/old*